parameters:
    sidus_eav_publishing.doctrine_orm.subscriber.class: Sidus\PublishingBundle\Event\ORMSubscriber
    sidus_eav_publishing.publisher.default.class: Sidus\PublishingBundle\Publishing\Publisher
    sidus_eav_publishing.pusher.rest.class: Sidus\PublishingBundle\Publishing\RestPusher

services:
    sidus_eav_publishing.doctrine_orm.subscriber:
        class: %sidus_eav_publishing.doctrine_orm.subscriber.class%
        arguments: [%kernel.debug%]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
