parameters:
    sidus_eav_publishing.publisher.default.class: Sidus\PublishingBundle\Publishing\Publisher

services:
    sidus_eav_publishing.doctrine_orm.subscriber:
        class: Sidus\PublishingBundle\Event\ORMSubscriber
        arguments: ['%kernel.debug%']
        tags:
            - { name: doctrine.event_subscriber, connection: default }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
